export * from "./recursion";
export * from "./clist";
export * from "./add-sub";
export * from "./compose";
export * from "./zip";
export * from "./zipmap";
export * from "./zipwith";
export * from "./car-cdr";
export * from "./partial";
